### PR TITLE
Application exit cli

### LINKED ISSUE #6: Application exit when entering a wrong command in the cli
#7 PR

### PR DESCRIPTION
**Pull request by Napokue**
Fixes #6

### CODE REVIEW

File: tron-cli/src/main/scala/org/tron/cli/App.scala [hunk 1]
```diff
@@ -15,21 +15,31 @@ object App {
...
-    cmd("exit").action( (_, c) => c.copy(command = Some(ExitCommand()))).
+    cmd("exit").action( (_, c) => doCopy(c, ExitCommand())).
       text("close tron")
   }
 
+  def doCopy(config: Config, command: Command): Config = {
+    config.copy(command = Some(command))
+  }
 
   def main(args: Array[String]) = {
```
Comment (Napokue) [inline tron-cli/src/main/scala/org/tron/cli/App.scala]: I do not know how to handle with the double `handleArgs(args)` - the first one is for the initialize of the application and the second for user input args.

Comment (Napokue) [reply tron-cli/src/main/scala/org/tron/cli/App.scala]: Removed the first handleArgs, it was used for initial args that were supplied when starting the application. We don't use startup arguments for now.

**Comment by Rovak** [comment]
LGTM!
